spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db_test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

logging:
  level:
    root: WARN
    com.workspace.auth: INFO